import { Metadata } from "next";
import Link from "next/link";
import "./global.css";
export const metadata: Metadata = {
  title: {
    default: "Imaginfolio",
    template: "%s | Imaginfolio",
  },
  description: "Generated by Next.js| RAGAdox",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ul className="flex flex-row justify-between bg-slate-400 mb-10">
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/about" replace>
              About Us
            </Link>
          </li>
          <li>
            <Link href="/profile" replace>
              Profile
            </Link>
          </li>
          <li>
            <Link href="/products" replace>
              Products
            </Link>
          </li>
        </ul>
        <div className="bg-slate-200">{children}</div>
      </body>
    </html>
  );
}
